CREATE TABLE combat_rules (
    id INTEGER PRIMARY KEY NOT NULL CHECK (id = 1),
    kill_bounty_multiplier REAL NOT NULL CHECK (typeof(kill_bounty_multiplier) IN ('integer', 'real') AND kill_bounty_multiplier >= 0),
    rout_bounty_multiplier REAL NOT NULL CHECK (typeof(rout_bounty_multiplier) IN ('integer', 'real') AND rout_bounty_multiplier >= 0),
    capture_bounty_multiplier REAL NOT NULL CHECK (typeof(capture_bounty_multiplier) IN ('integer', 'real') AND capture_bounty_multiplier >= 0),
    morale_max REAL NOT NULL CHECK (typeof(morale_max) IN ('integer', 'real') AND morale_max > 0),
    base_morale_regen_per_second REAL NOT NULL CHECK (typeof(base_morale_regen_per_second) IN ('integer', 'real') AND base_morale_regen_per_second > 0),
    break_morale_splash REAL NOT NULL CHECK (typeof(break_morale_splash) IN ('integer', 'real') AND break_morale_splash >= 0),
    break_splash_radius REAL NOT NULL CHECK (typeof(break_splash_radius) IN ('integer', 'real') AND break_splash_radius > 0),
    wavering_splash_multiplier REAL NOT NULL CHECK (typeof(wavering_splash_multiplier) IN ('integer', 'real') AND wavering_splash_multiplier >= 0),
    shaken_speed_multiplier REAL NOT NULL CHECK (typeof(shaken_speed_multiplier) IN ('integer', 'real') AND shaken_speed_multiplier >= 0 AND shaken_speed_multiplier <= 1),
    rout_speed_multiplier REAL NOT NULL CHECK (typeof(rout_speed_multiplier) IN ('integer', 'real') AND rout_speed_multiplier > 0),
    steady_advance_hp_gate REAL NOT NULL CHECK (typeof(steady_advance_hp_gate) IN ('integer', 'real') AND steady_advance_hp_gate >= 0 AND steady_advance_hp_gate <= 1),
    contagion_tick_interval REAL NOT NULL CHECK (typeof(contagion_tick_interval) IN ('integer', 'real') AND contagion_tick_interval > 0),
    disease_hp_per_second REAL NOT NULL CHECK (typeof(disease_hp_per_second) IN ('integer', 'real') AND disease_hp_per_second >= 0),
    disease_hp_floor_fraction REAL NOT NULL CHECK (typeof(disease_hp_floor_fraction) IN ('integer', 'real') AND disease_hp_floor_fraction >= 0 AND disease_hp_floor_fraction <= 1),
    disease_morale_per_second REAL NOT NULL CHECK (typeof(disease_morale_per_second) IN ('integer', 'real') AND disease_morale_per_second >= 0),
    contagion_spread_radius REAL NOT NULL CHECK (typeof(contagion_spread_radius) IN ('integer', 'real') AND contagion_spread_radius > 0),
    contagion_spread_chance REAL NOT NULL CHECK (typeof(contagion_spread_chance) IN ('integer', 'real') AND contagion_spread_chance >= 0 AND contagion_spread_chance <= 1),
    melee_attack_spread REAL NOT NULL CHECK (typeof(melee_attack_spread) IN ('integer', 'real') AND melee_attack_spread >= 0 AND melee_attack_spread <= 1),
    melee_move_speed REAL NOT NULL CHECK (typeof(melee_move_speed) IN ('integer', 'real') AND melee_move_speed > 0),
    melee_engage_scan_radius_fraction REAL NOT NULL CHECK (typeof(melee_engage_scan_radius_fraction) IN ('integer', 'real') AND melee_engage_scan_radius_fraction > 0 AND melee_engage_scan_radius_fraction <= 1),
    melee_reach REAL NOT NULL CHECK (typeof(melee_reach) IN ('integer', 'real') AND melee_reach > 0),
    melee_combat_spacing REAL NOT NULL CHECK (typeof(melee_combat_spacing) IN ('integer', 'real') AND melee_combat_spacing > 0),
    melee_leash_radius_fraction REAL NOT NULL CHECK (typeof(melee_leash_radius_fraction) IN ('integer', 'real') AND melee_leash_radius_fraction > 0 AND melee_leash_radius_fraction <= 1),
    enemy_swing_interval REAL NOT NULL CHECK (typeof(enemy_swing_interval) IN ('integer', 'real') AND enemy_swing_interval > 0),
    hero_engage_scan_radius REAL NOT NULL CHECK (typeof(hero_engage_scan_radius) IN ('integer', 'real') AND hero_engage_scan_radius > 0),
    hero_leash_radius REAL NOT NULL CHECK (typeof(hero_leash_radius) IN ('integer', 'real') AND hero_leash_radius > 0),
    melee_post_spread REAL NOT NULL CHECK (typeof(melee_post_spread) IN ('integer', 'real') AND melee_post_spread >= 0),
    melee_spawn_spread REAL NOT NULL CHECK (typeof(melee_spawn_spread) IN ('integer', 'real') AND melee_spawn_spread >= 0),
    arrival_radius REAL NOT NULL CHECK (typeof(arrival_radius) IN ('integer', 'real') AND arrival_radius > 0),
    range_vertical_fraction REAL NOT NULL CHECK (typeof(range_vertical_fraction) IN ('integer', 'real') AND range_vertical_fraction > 0 AND range_vertical_fraction <= 1),
    projectile_hit_radius REAL NOT NULL CHECK (typeof(projectile_hit_radius) IN ('integer', 'real') AND projectile_hit_radius > 0),
    grapeshot_hit_radius REAL NOT NULL CHECK (typeof(grapeshot_hit_radius) IN ('integer', 'real') AND grapeshot_hit_radius > 0),
    solid_shot_hit_radius REAL NOT NULL CHECK (typeof(solid_shot_hit_radius) IN ('integer', 'real') AND solid_shot_hit_radius > 0),
    firing_tolerance_degrees REAL NOT NULL CHECK (typeof(firing_tolerance_degrees) IN ('integer', 'real') AND firing_tolerance_degrees > 0 AND firing_tolerance_degrees <= 180),
    initial_heading_degrees REAL NOT NULL CHECK (typeof(initial_heading_degrees) IN ('integer', 'real') AND initial_heading_degrees >= -180 AND initial_heading_degrees <= 180),
    enemy_body_offset_x REAL NOT NULL CHECK (typeof(enemy_body_offset_x) IN ('integer', 'real') AND enemy_body_offset_x >= -1000000),
    enemy_body_offset_y REAL NOT NULL CHECK (typeof(enemy_body_offset_y) IN ('integer', 'real') AND enemy_body_offset_y >= -1000000),
    morale_visibility_threshold REAL NOT NULL CHECK (typeof(morale_visibility_threshold) IN ('integer', 'real') AND morale_visibility_threshold >= 0),
    morale_response_duration REAL NOT NULL CHECK (typeof(morale_response_duration) IN ('integer', 'real') AND morale_response_duration > 0),
    morale_recovery_delay REAL NOT NULL CHECK (typeof(morale_recovery_delay) IN ('integer', 'real') AND morale_recovery_delay >= 0),
    morale_display_duration REAL NOT NULL CHECK (typeof(morale_display_duration) IN ('integer', 'real') AND morale_display_duration > 0),
    reinforcement_soldier_count INTEGER NOT NULL CHECK (typeof(reinforcement_soldier_count) = 'integer' AND reinforcement_soldier_count > 0),
    grapeshot_spread_degrees TEXT NOT NULL CHECK (json_valid(grapeshot_spread_degrees)),
    CHECK (morale_visibility_threshold <= morale_max)
);
