-- Generated by Tools/generate_level_02_waves.py. Do not hand-edit.
-- Bunker Hill: eight compact early-game waves over the main assault (path 0)
-- and Mystic flank (path 1). The roster is limited to British units present
-- or representative of the 17 June 1775 assault: regulars, light infantry,
-- grenadiers, and a regimental drummer.

DELETE FROM level_wave_enemy_spawn WHERE level_wave_id IN (
    SELECT id FROM level_wave WHERE level_info_id = '9d692af7-345d-419a-bc04-16112c3f0b74'
);
DELETE FROM level_wave WHERE level_info_id = '9d692af7-345d-419a-bc04-16112c3f0b74';

INSERT INTO level_wave (id, level_info_id, wave_index, spawn_time) VALUES
('065cccea-1b0e-52ca-9d1c-124fb065f0e9', '9d692af7-345d-419a-bc04-16112c3f0b74', 1, 5.0),
('58f1025c-dc63-50a8-a1dc-d7ab7851ced4', '9d692af7-345d-419a-bc04-16112c3f0b74', 2, 30.0),
('11ccb1b1-8985-5b1d-ab03-ad987274f2df', '9d692af7-345d-419a-bc04-16112c3f0b74', 3, 55.0),
('d8edaf80-94e0-51d7-9429-af9eb7123848', '9d692af7-345d-419a-bc04-16112c3f0b74', 4, 80.0),
('7fc65ede-e8ad-5c4d-884d-8c0daceb4f00', '9d692af7-345d-419a-bc04-16112c3f0b74', 5, 105.0),
('fc699725-9751-530b-a2e2-1b5e74ea3659', '9d692af7-345d-419a-bc04-16112c3f0b74', 6, 130.0),
('b24d66ad-e3e5-586d-8aa3-16f7887635e5', '9d692af7-345d-419a-bc04-16112c3f0b74', 7, 155.0),
('d7571939-420d-5a24-942d-65ea35d9f997', '9d692af7-345d-419a-bc04-16112c3f0b74', 8, 180.0);

INSERT INTO level_wave_enemy_spawn (
    id, level_wave_id, enemy_type_id, spawn_index,
    num_enemies, spawn_time_since_previous_spawn, spawn_interval, path_index
) VALUES
('73f15250-0e67-5c79-86e1-9e95cc793d50', '065cccea-1b0e-52ca-9d1c-124fb065f0e9', (SELECT id FROM enemy_type WHERE enemy_type_name = 'Redcoat Regular'), 0, 4, 0.0, 1.15, 0),
('98ef01fc-6592-5f10-b51b-dccd151a026d', '58f1025c-dc63-50a8-a1dc-d7ab7851ced4', (SELECT id FROM enemy_type WHERE enemy_type_name = 'Redcoat Regular'), 0, 5, 0.0, 1.05, 0),
('b7c3bb8b-d409-5e29-b978-22286c65ad09', '11ccb1b1-8985-5b1d-ab03-ad987274f2df', (SELECT id FROM enemy_type WHERE enemy_type_name = 'Light Infantry'), 0, 5, 0.0, 1.00, 1),
('fb923af1-e1b8-5bf3-a722-a910c90e3943', 'd8edaf80-94e0-51d7-9429-af9eb7123848', (SELECT id FROM enemy_type WHERE enemy_type_name = 'Redcoat Regular'), 0, 5, 0.0, 1.00, 0),
('3e10e637-0a32-5dae-a9d7-bd3c6c4c3fcc', 'd8edaf80-94e0-51d7-9429-af9eb7123848', (SELECT id FROM enemy_type WHERE enemy_type_name = 'Light Infantry'), 1, 4, 0.0, 0.95, 1),
('f98d6d11-5127-5e4b-ad91-70650518ec1b', '7fc65ede-e8ad-5c4d-884d-8c0daceb4f00', (SELECT id FROM enemy_type WHERE enemy_type_name = 'Redcoat Regular'), 0, 6, 0.0, 0.95, 0),
('8a97388c-f30c-5d6f-a493-fb7f0438c8d0', '7fc65ede-e8ad-5c4d-884d-8c0daceb4f00', (SELECT id FROM enemy_type WHERE enemy_type_name = 'Light Infantry'), 1, 5, 2.0, 0.90, 1),
('fc4ed672-1df2-557c-bb02-fce840e85b17', 'fc699725-9751-530b-a2e2-1b5e74ea3659', (SELECT id FROM enemy_type WHERE enemy_type_name = 'Regimental Drummer'), 0, 1, 0.0, 1.00, 0),
('e6365a5f-07fe-5e88-9de5-1ce700369b67', 'fc699725-9751-530b-a2e2-1b5e74ea3659', (SELECT id FROM enemy_type WHERE enemy_type_name = 'Redcoat Regular'), 0, 6, 0.0, 0.90, 0),
('e635dddf-b747-524d-a667-c1c56f8ddc06', 'fc699725-9751-530b-a2e2-1b5e74ea3659', (SELECT id FROM enemy_type WHERE enemy_type_name = 'Light Infantry'), 1, 5, 3.0, 0.85, 1),
('c06b1aca-36e3-5c51-b906-c3906993094e', 'b24d66ad-e3e5-586d-8aa3-16f7887635e5', (SELECT id FROM enemy_type WHERE enemy_type_name = 'Grenadier'), 0, 2, 0.0, 1.45, 0),
('8827d9b7-3e11-5155-a9d1-64c39529cf45', 'b24d66ad-e3e5-586d-8aa3-16f7887635e5', (SELECT id FROM enemy_type WHERE enemy_type_name = 'Redcoat Regular'), 0, 6, 0.0, 0.88, 0),
('98f019bd-21f1-5b70-a889-177d281a4775', 'b24d66ad-e3e5-586d-8aa3-16f7887635e5', (SELECT id FROM enemy_type WHERE enemy_type_name = 'Light Infantry'), 1, 5, 2.0, 0.82, 1),
('501c4eb8-41bb-5bc6-9086-c01736ccb081', 'd7571939-420d-5a24-942d-65ea35d9f997', (SELECT id FROM enemy_type WHERE enemy_type_name = 'Regimental Drummer'), 0, 1, 0.0, 1.00, 1),
('cbe9f821-cc3e-5b24-86b4-517d460a602b', 'd7571939-420d-5a24-942d-65ea35d9f997', (SELECT id FROM enemy_type WHERE enemy_type_name = 'Redcoat Regular'), 0, 7, 0.0, 0.85, 1),
('fceda826-c9a8-54a2-a90f-3298c5775353', 'd7571939-420d-5a24-942d-65ea35d9f997', (SELECT id FROM enemy_type WHERE enemy_type_name = 'Grenadier'), 1, 3, 3.0, 1.35, 0),
('30350f3c-6f94-50b3-8b87-72a1bc3a8ceb', 'd7571939-420d-5a24-942d-65ea35d9f997', (SELECT id FROM enemy_type WHERE enemy_type_name = 'Light Infantry'), 2, 6, 4.0, 0.80, 1);
