-- Encyclopedia history is authored independently of gameplay effects.
-- Named units describe the original formation; other entries explain the
-- period weapon or role that inspired the tower. Sources checked 2026-09-21.
INSERT INTO tower_history (tower_id, historical_description, source_title, source_url, presentation_kind, strategy_text, inclusion_reason) VALUES
('0a4b1c62-8f3e-4d97-b120-6e5a9c8d7f01',
 'Smoothbore flintlock muskets armed most Revolutionary infantry. Trained soldiers could fire several rounds a minute, making coordinated volleys more practical than distant, precise shots.',
 'National Park Service · Black Powder Weapons',
 'https://www.nps.gov/articles/000/black-powder-weapons-of-the-southern-campaign.htm', 'standard', NULL, NULL),
('1b5c2d73-9a4f-4ea8-8c31-7f6b0d9e8a02',
 'This tower represents skilled shooters rather than a named regiment. Revolutionary riflemen could aim farther than musket troops, but their weapons took longer to reload.',
 'National Park Service · Black Powder Weapons',
 'https://www.nps.gov/articles/000/black-powder-weapons-of-the-southern-campaign.htm', 'standard', NULL, NULL),
('2c6d3e84-0b5a-4fb9-9d42-8a7c1e0f9b03',
 'Spiral grooves inside a rifle barrel spun the ball for greater accuracy. Civilian hunting rifles entered military service, giving practiced shooters an advantage at longer ranges.',
 'National Park Service · Black Powder Weapons',
 'https://www.nps.gov/articles/000/black-powder-weapons-of-the-southern-campaign.htm', 'standard', NULL, NULL),
('1008b722-563a-44a0-8b31-c9cca93b9927',
 'Daniel Morgan led a selected rifle corps in 1777. Paired with Henry Dearborn’s light infantry, his men played an important part in the American victory at Saratoga.',
 'National Park Service · Daniel Morgan',
 'https://www.nps.gov/sara/learn/historyculture/daniel-morgan.htm', 'standard', NULL, NULL),
('72788425-7677-418a-a06c-6b3120f94631',
 'Thomas Knowlton’s rangers scouted British positions for Washington in 1776. Their reconnaissance helped trigger the Battle of Harlem Heights, where Knowlton was mortally wounded.',
 'U.S. Army Intelligence Center · Knowlton at Harlem Heights',
 'https://www.dvidshub.net/news/574456/lt-col-knowlton-falls-harlem-heights-16-sep-1776', 'standard', NULL, NULL),
('c5cc2d7b-b08c-4ba7-a532-52ba070589a5',
 'Congress authorized Whitcomb’s Rangers in October 1776 for the Continental Army’s Northern Department. The independent formation grew from the northern war’s need for scouting troops.',
 'U.S. Army Center of Military History · The Continental Army',
 'https://history.army.mil/portals/143/Images/Publications/catalog/60-4-1.pdf', 'standard', NULL, NULL),
('3d7e4f95-1c6b-4ac0-ae53-9b8d2f1a0c04',
 'Massachusetts militia companies were part-time local defenders. Towns required eligible men to keep arms and train, providing an immediate force when their communities faced attack.',
 'National Park Service · Militia and Minute Men',
 'https://www.nps.gov/mima/learn/historyculture/the-militia-and-minute-men-of-1775.htm', 'standard', NULL, NULL),
('4e8f5a06-2d7c-4bd1-bf64-0c9e3a2b1d05',
 'Massachusetts minute men volunteered to march at short notice. They trained more often than ordinary militia and helped answer the British advance on April 19, 1775.',
 'National Park Service · Militia and Minute Men',
 'https://www.nps.gov/mima/learn/historyculture/the-militia-and-minute-men-of-1775.htm', 'standard', NULL, NULL),
('5f9a6b17-3e8d-4ce2-c075-1d0f4b3c2e06',
 'Congress created the Continental Army in June 1775, uniting colonial forces in a common army. Its regiments sustained a national war effort beyond each colony’s local defense.',
 'U.S. Army Center of Military History · Continental Army',
 'https://history.army.mil/Explore-Army-History/Founding-the-Nation/Commemoration/Revolutionary-War/Continental-Army/', 'standard', NULL, NULL),
('9c1aa74b-b783-4fc1-b9c3-daeaf5284146',
 'At Valley Forge in 1778, Baron von Steuben taught a model company standardized drills. Those soldiers spread the lessons, helping Continental regiments maneuver together with greater discipline.',
 'National Park Service · General von Steuben',
 'https://www.nps.gov/vafo/learn/historyculture/vonsteuben.htm', 'standard', NULL, NULL),
('634b9957-dce1-4b53-8665-1017904ad89d',
 'Continental light infantry undertook demanding assaults. In July 1779, Anthony Wayne’s specially trained corps captured Stony Point in a night attack led with bayonets.',
 'New York State Parks · Stony Point Battlefield',
 'https://parks.ny.gov/visit/historic-sites/stony-point-battlefield-state-historic-site', 'standard', NULL, NULL),
('550638ec-0f26-4329-9719-2d3f2e697238',
 'Maryland troops won renown at the Battle of Brooklyn in 1776. Their repeated attacks, alongside Delaware soldiers, helped other Americans withdraw while suffering heavy losses themselves.',
 'National Park Service · The Maryland 400',
 'https://www.nps.gov/articles/000/the-maryland-400.htm', 'standard', NULL, NULL),
('6a0b7c28-4f9e-4df3-d186-2e1a5c4d3f07',
 'French four-pounder field guns served the Continental Army. Surviving examples show that some barrels were enlarged to fire British six-pounder ammunition, easing the problem of mixed supplies.',
 'National Park Service · French Four-Pounder Field Gun',
 'https://www.nps.gov/spar/learn/historyculture/french-field_4pdr.htm', 'standard', NULL, NULL),
('7b1c8d39-5a0f-4ea4-e297-3f2b6d5e4a08',
 'A six-pounder took its name from its solid iron shot. British forces brought these field guns into both battles at Saratoga in September and October 1777.',
 'National Park Service · Saratoga Collections',
 'https://www.nps.gov/sara/learn/historyculture/collections.htm', 'standard', NULL, NULL),
('8c2d9e40-6b1a-4fb5-f3a8-4a3c7e6f5b09',
 'Howitzers combined a field carriage with the ability to lob explosive shells. At Yorktown, they worked alongside cannon and mortars to bombard defended positions.',
 'National Park Service · Revolutionary War Artillery',
 'https://www.nps.gov/york/learn/historyculture/revolutionary-war-artillery.htm', 'standard', NULL, NULL),
('f614aea2-b5cb-4cd3-a30d-e33a02c27c90',
 'At Yorktown in 1781, American, French and British artillery included cannon, howitzers and mortars. A mortar sat on a wooden bed; its elevated barrel sent an explosive shell high over defensive earthworks. Cannon firing along a flatter path faced a different problem: walls and earth could shield the defenders.

Mortar crews judged elevation, powder and the shell fuse. Effective bombardment depended on their skill. These were siege weapons used against defended positions, not rapid-firing field guns.',
 'National Park Service · Revolutionary War Artillery',
 'https://www.nps.gov/york/learn/historyculture/revolutionary-war-artillery.htm', 'mortarStudy',
 'Place the battery where several enemies will be close together when a shell lands. Infantry holding a choke point or engineers slowing an approach can keep more targets inside the same blast.

Damage falls with distance from the impact, so enemies near the edge take less. The pause between shells gives separated enemies time to advance; support the battery with a faster-firing tower. Morale shock can disrupt a group before every soldier is defeated.',
 'We included the Mortar Battery to give Revolutionary siege artillery a distinct place in the roster: one carefully placed explosion can disrupt a formation. It rewards arranging a defended approach and combining artillery with troops who hold or slow the enemy.

Its rapid reload, impact explosions, targeting and numerical ranges are gameplay abstractions. The real weapons fired fused shells on high trajectories; this game does not simulate historical ballistics.'),
('01b02f93-d2ff-4754-9072-35a1aa65cd6d',
 'Swivel guns were small cannon on rotating mounts. Crews could turn them quickly and fire canister or grapeshot against infantry from positions larger guns could not reach.',
 'National Park Service · Black Powder Weapons',
 'https://www.nps.gov/articles/000/black-powder-weapons-of-the-southern-campaign.htm', 'standard', NULL, NULL),
('fa950e72-3c9c-420a-ab60-b40cb41407cf',
 'An 18-pounder fired a solid iron ball weighing about eighteen pounds. Heavy siege guns battered buildings and fortifications. At Yorktown in 1781, the allied siege train and skilled gun crews helped force the British surrender.

The ball did not burst like a mortar shell. Its destructive force came from its weight and speed. Round shot could continue through troops in its line of flight; firing along a formation exposed several men to the same ball.',
 'National Park Service · Revolutionary War Artillery',
 'https://www.nps.gov/york/learn/historyculture/revolutionary-war-artillery.htm', 'siegeStudy',
 'Place the battery beside a bend where the gun can fire through several enemies along one line. Rally infantry ahead of it to hold that formation while the crew aims and reloads.

The round shot continues through enemies it strikes. Enemies beside its flight line are not caught in a circular explosion. Leave room for the slow gun to turn, and protect the approach during its reload.',
 'We included the 18-Pounder Siege Battery to represent the heavy guns that made Revolutionary siege warfare decisive. Its penetrating shot gives positioning a different purpose: one firing line can expose several enemies to the same heavy ball.

The demonstration translates that effect into a defended road bend. Infantry blocking, a short reload and the absence of friendly fire are gameplay abstractions; this is not a reconstruction of firing into a historical melee. Fortification breaching and ground ricochets are not simulated here.'),
('9d3e0f51-7c2b-4ac6-a4b9-5b4d8f7a6c10',
 'The Continental Army needed engineers from its beginning in 1775. Its chief engineer and assistants planned fortifications, turning labor and local materials into protection for soldiers.',
 'U.S. Army Corps of Engineers · Charleston District History',
 'https://www.sac.usace.army.mil/About/History/', 'standard', NULL, NULL),
('0e4f1a62-8d3c-4bd7-b5c0-6c5e9a8b7d11',
 'Engineers helped shape the battlefield before troops fought. Under Louis Duportail, they planned defenses and directed the siegeworks that brought allied forces closer to Yorktown’s walls.',
 'U.S. Army · Sapper History',
 'https://www.army.mil/sapper/history.html', 'standard', NULL, NULL),
('1f5a2b73-9e4d-4ce8-c6d1-7d6f0b9c8e12',
 'Sappers dug protected approaches toward enemy fortifications. Congress authorized American sapper companies in 1778, providing soldiers trained for the dangerous work of military engineering.',
 'U.S. Army · Sapper History',
 'https://www.army.mil/sapper/history.html', 'standard', NULL, NULL),
('01b5f5d5-5472-4dbd-be95-9089af603422',
 'This tower draws on Revolutionary field defenses. At Yorktown, sharpened branches called abatis obstructed approaches to redoubts, making attackers struggle through obstacles under fire.',
 'U.S. Army Heritage and Education Center · Yorktown Redoubt No. 10',
 'https://history.army.mil/Army-Museum-Enterprise/Find-an-Army-Museum/US-Army-Heritage-and-Education-Center/Army-Heritage-Trail/YorktownRedoubtNo10/', 'standard', NULL, NULL),
('44c58827-2c6c-4ec4-a2f2-43473908aee8',
 'Siege engineers used gunpowder charges beneath fortifications to break walls. This tower adapts that older siegecraft tradition; its automatic roadside charge is a game invention.',
 'U.S. Army · Sapper History',
 'https://www.army.mil/sapper/history.html', 'standard', NULL, NULL),
('e6a89c04-b291-4f37-8ad2-0196f75c4301',
 'Wagons, horses and boats kept Washington’s army moving. Shortages of transport could strand essential supplies, making the humble supply train as necessary as the troops it served.',
 'U.S. Army Quartermaster Museum · Supplying the Continental Army',
 'https://qmmuseum.army.mil/research/history-heritage/history/Nathanael-Green-and-the-Supply-of-the-Continental-Army.html', 'standard', NULL, NULL),
('e6a89c04-b291-4f37-8ad2-0196f75c4302',
 'Nathanael Greene favored many small supply depots over a few large ones. Dispersed stores helped the army shift position and reduced the danger of losing everything in a raid.',
 'U.S. Army Quartermaster Museum · Supplying the Continental Army',
 'https://qmmuseum.army.mil/research/history-heritage/history/Nathanael-Green-and-the-Supply-of-the-Continental-Army.html', 'standard', NULL, NULL),
('e6a89c04-b291-4f37-8ad2-0196f75c4303',
 'Commissary staff purchased, packed and issued the army’s food. At Valley Forge, improved purchasing and delivery gradually eased shortages that had threatened the encampment in early 1778.',
 'National Park Service · The Commissary Department',
 'https://www.nps.gov/articles/000/the-commissary-department.htm', 'standard', NULL, NULL),
('e6a89c04-b291-4f37-8ad2-0196f75c4401',
 'As quartermaster general from 1778, Nathanael Greene rebuilt an ailing supply system. Organizing transport, forage and camp equipment helped Washington’s army take the field again.',
 'U.S. Army Quartermaster Museum · Supplying the Continental Army',
 'https://qmmuseum.army.mil/research/history-heritage/history/Nathanael-Green-and-the-Supply-of-the-Continental-Army.html', 'standard', NULL, NULL),
('e6a89c04-b291-4f37-8ad2-0196f75c4402',
 'The Continental arsenal at Springfield began operating in 1777. Workers made ammunition, repaired weapons, maintained artillery and stored supplies that kept the army equipped for battle.',
 'National Park Service · Springfield Armory',
 'https://www.nps.gov/spar/faqs.htm', 'standard', NULL, NULL),
('e6a89c04-b291-4f37-8ad2-0196f75c4403',
 'Armies converted buildings into hospitals for sick and wounded soldiers. In 1776, American physicians used the unfinished St. Paul’s Church in Eastchester as a military hospital.',
 'National Park Service · St. Paul’s Field Hospital',
 'https://www.nps.gov/articles/000/directors-of-the-american-field-hospital-at-st-paul-s-during-the-revolutionary-war.htm', 'standard', NULL, NULL);


INSERT INTO tower_history (tower_id, historical_description, source_title, source_url, presentation_kind, strategy_text, inclusion_reason) VALUES
('8de0f7a6-1152-4c49-bf35-623ac190a401',
 'Cast-iron hand grenades were used during the American Revolution, including close fighting between ships. The Smithsonian describes their use in the battle between Bonhomme Richard and Serapis. Grenadier Redoubt is a fictional composite unit inspired by that weapon, not a named Continental regiment. Its automatic attacks, range, blast and morale effects are gameplay abstractions.',
 'Smithsonian National Museum of American History · Grenade',
 'https://americanhistory.si.edu/collections/object/nmah_458176', 'standard', NULL, NULL);
